#!/bin/bash

# Environment Configuration Script
# Usage: ./scripts/set-env.sh [development|staging|production] [mock|real]

set -e

ENV=${1:-development}
API_TYPE=${2:-mock}

echo "🔧 Configuring environment for: $ENV with $API_TYPE API"

# Create .env.local based on parameters
cat > .env.local << EOF
# Generated by set-env.sh script
# Environment: $ENV
# API Type: $API_TYPE
# Generated at: $(date)

NEXT_PUBLIC_ENVIRONMENT=$ENV
NEXT_PUBLIC_USE_MOCK_API=$([ "$API_TYPE" = "mock" ] && echo "true" || echo "false")
EOF

# Set API URL based on environment
case $ENV in
  development)
    echo "NEXT_PUBLIC_API_URL=http://localhost:3001/api" >> .env.local
    ;;
  staging)
    echo "NEXT_PUBLIC_API_URL=https://api-staging.yourapp.com" >> .env.local
    ;;
  production)
    echo "NEXT_PUBLIC_API_URL=https://api.yourapp.com" >> .env.local
    ;;
  *)
    echo "❌ Unknown environment: $ENV"
    echo "Available environments: development, staging, production"
    exit 1
    ;;
esac

echo ""
echo "✅ Configuration updated!"
echo "📁 Current .env.local contents:"
echo "================================="
cat .env.local
echo "================================="
echo ""

if [ "$API_TYPE" = "mock" ]; then
  echo "🎭 Using mock API - no backend required"
else
  echo "🌐 Using real API - make sure your backend is running"
fi

echo ""
echo "🚀 Restart your development server to apply changes:"
echo "   npm run dev"
